Code reorganization, better error condition output, internalize some functionality in order to avoid process spawning overhead, improve robustness a bit.

diff --git a/editdns b/editdns
--- a/editdns
+++ b/editdns
@@ -11,16 +11,14 @@
 # Note: Except when called with the --list option, this script requires root privileges
 #
 
-# default BIND configuration file is /etc/named.conf
-BINDconf=${BIND_CONF:-${ROOT:-/}etc/named.conf}
-
-# default zone file location from the BIND configuration
-dbDir=$(awk '/^[[:space:]]+directory/{print $2}' ${BINDconf} | tr -d '[";]')
-
-# set the defalt editor their preference, else vi
-EDITOR=${VISUAL:-${EDITOR:-vi}}
-
 zmodload zsh/stat
+zmodload zsh/termcap
+
+##############################################################################
+#
+# Function Definitions
+#
+##############################################################################
 
 usage () {
 
@@ -28,10 +26,10 @@ usage () {
 Usage: editdns [ --verbose ] [ --list ] [ --editor <editor> ] [ domain-name ]
 
 Options:
---editor (-e)	Specify an editor (vi, nano, pico, etc.)
---help (-h)	This help
---list (-l)	List all configured zones
---verbose (-v)	Be chatty about what is going on
+--editor (-e)   Specify an editor (vi, nano, pico, etc.)
+--help (-h)     This help
+--list (-l)     List all configured zones
+--verbose (-v)  Be chatty about what is going on
 
 - When called with --list (-l) the 'zone-name' parameter is ignored and you do not need root credentials.
 - The --editor (-e) named must exist as an executable in /bin or /usr/bin
@@ -51,12 +49,13 @@ in-addrsort () {
 
 # return the full path to the zone file for the named zone (domain)
 getZoneFile () {
-  local zoneName=${1:?"Name a domain for which to retrieve a zone file."}
+  local domainName=${1:?"Name a domain for which to retrieve a zone file."}
   local returnValue=0
 
-  (( VERBOSE )) && echo "Getting zone filename for domain ${zoneName}." >&2
+  (( VERBOSE )) && echo "Getting zone filename for domain ${domainName}." >&2
   # get the zone file
-  if zoneFile=$(egrep -A 3 "^zone[[:space:]]+\"${zoneName}\"" ${BINDconf} | egrep '^[[:space:]]+file' | head -n 1 | cut -d'"' -f2)
+  # BUG ALERT: this is totally dependent on the placement of the 'file' option inside 'zone' clauses
+  if zoneFile=$(egrep -A 3 "^zone[[:space:]]+\"${domainName}\"" ${BINDconf} | egrep '^[[:space:]]+file' | head -n 1 | cut -d'"' -f2)
   then
     if test -n "${zoneFile}"
     then
@@ -65,22 +64,22 @@ getZoneFile () {
       # prepend dbDir if zoneFile is a relative pathname
       if expr match ${zoneFile} '[^/]' > /dev/null
       then
-	zoneFile=${dbDir}/${zoneFile}
-	(( VERBOSE )) && echo "Full path to zone file: ${zoneFile}." >&2
+        zoneFile=${dbDir}/${zoneFile}
+        (( VERBOSE )) && echo "Full path to zone file: ${zoneFile}." >&2
       fi
       if test -r ${zoneFile}
       then
-	echo ${zoneFile}
+        echo ${zoneFile}
       else
-	echo "Configuration file ${zoneFile} for ${zoneName} not found in ${dbDir}." >&2
-	returnValue=3
+        echo "${0}: Error (3): Configuration file ${zoneFile} for ${domainName} not found in ${dbDir}." >&2
+        returnValue=3
       fi
     else
-      echo "Was not able to get a zone file name frome ${BINDconf}." >&2
+      echo "${0}: Error (2): Unable to get a zone file name for domain ${domainName} from ${BINDconf}." >&2
       returnValue=2
     fi
   else
-    echo "Configuration file for ${zoneName} not found." >&2
+    echo "${0}: Error (1): Zone file configuration for ${domainName} not found in ${BINDconf}." >&2
     returnValue=1
   fi
 
@@ -100,7 +99,7 @@ newSerialNumber() {
   # Note that this presumes all zone files have been touched since 1999
   # This also strips any comments from the end of the line containing the serial number
   serial=$(pcregrep -o '^\s+20[0-9][0-9][0-9][0-9][0-9][0-9][0-9]{1,2}' ${zoneFileName} | tr -d '[[:space:]]' | sed -r -e 's/[[:space:]]*;.*//')
-  (( VERBOSE )) && echo "current serial number for ${zoneFileName}: ${serial} \c" >&2
+  (( VERBOSE )) && echo "Current serial number for ${zoneFileName}: ${serial} \c" >&2
   # lop off the two-digit index
   serialDate=${serial%??}
   if (( serialDate == today ))
@@ -109,9 +108,10 @@ newSerialNumber() {
   else
     newSerial=${today}${index}
   fi
-  (( VERBOSE )) && echo "new serial number: ${newSerial}" >&2
+  (( VERBOSE )) && echo "New serial number: ${newSerial}" >&2
 
   # replace the serial number in the zone file
+  # Note: this function exits with the exit value of the sed(1) command; errors are handled in the calling context
   sed -i -r -e "s/^([[:space:]]+)20[0-9][0-9][0-9][0-9][0-9][0-9][0-9]{1,2}/\1${newSerial}/" ${zoneFileName}
 }
 
@@ -147,6 +147,32 @@ pushChanges() {
   return $returnValue;
 }
 
+##############################################################################
+#
+# Global Variables
+#
+##############################################################################
+
+# high-powered graphics, see zshmodules(1) and termcap(5) for details
+BOLD="${termcap[md]}"
+NORMAL="${termcap[me]}"
+
+# default BIND configuration file is /etc/named.conf, exit if it is not readable
+BINDconf=${BIND_CONF:-${ROOT:-/}etc/named.conf}
+test -r "${BINDconf}" || { echo "Error (0): Cannot find ${BINDconf}" ; exit ; }
+
+# default zone file location from the BIND configuration
+dbDir=$(awk '/^[[:space:]]+directory/{print $2}' ${BINDconf} | tr -d '[";]')
+
+# set the defalt editor their preference, else vi
+EDITOR=${VISUAL:-${EDITOR:-vi}}
+
+##############################################################################
+#
+# Script Main Line
+#
+##############################################################################
+
 # use getopt to parse the command line args
 TEMP=$(getopt -o e:hlv --long editor:,help,list-files,verbose -n ${0:t} -- "${@}")
 if [ ${?} != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
@@ -166,181 +192,128 @@ done
 
 if test -n "${LISTZONES}"
 then
+
+  # this does not need elevated privileges
+
   for domain in $(awk '/^zone[[:space:]]/{print $2}' ${BINDconf} | tr -d '"' | ipsort | uniq)
   do
     zoneFile=$(grep -A 3 "${domain}" ${BINDconf} | awk '/^[[:space:]]+file[[:space:]]/{print $2}' | tr -d '[";]' | head -n 1)
     stat -s -H zoneFileMeta ${zoneFile}
     printf '%42s: %10s %8s %-8s %19s %s\n' ${domain} ${zoneFileMeta[mode]} ${zoneFileMeta[uid]} ${zoneFileMeta[gid]} ${zoneFileMeta[mtime]} ${zoneFile}
   done
+
 else
 
-  DOMAIN=${1:?"Please specify a domain name to edit."}
+  # from here to the end of the script requires elevated privileges
 
-  # determine the full path to the chosen editor
-  if test -n "${editor}"
+  DOMAIN=${1}
+  if test -n "${DOMAIN}"
   then
-    choices=( $(whence ${editor}) )
-    for choice in ${choices}
-    do
-      if test -x ${choice}
-      then
-        export EDITOR=${choice:t}
-        export VISUAL=${choice:t}
-        export SUDO_EDITOR=${choice:t}
-      fi
-    done
-  fi
 
-  LOCKFILE=${TMP:-${ROOT:-/}tmp}/${DOMAIN}.lock
-  if test -r ${LOCKFILE}
-  then
-    echo "Found existing lock file. If you are certain nobody is editing this zone file, remove ${LOCKFILE} and try again."
-  else
-
-    # remove the lock file under most exit conditions
-    trap "rm -f ${LOCKFILE} ; exit ;" 0 1 2 15
-
-    if zoneFile=$(getZoneFile ${DOMAIN})
+    # determine the full path to the chosen editor
+    if test -n "${editor}"
     then
-      # get current zone file meta info (owner, group, perms, etc.)
-      stat -o -H zoneFileMeta ${zoneFile}
-
-      if TMPZONEFILE=$(mktemp -t ${zoneFile:t}-XXXXXXX)
-      then
-        if cp -p ${zoneFile} ${TMPZONEFILE}
+      choices=( $(whence ${editor}) )
+      for choice in ${choices}
+      do
+        if test -x ${choice}
         then
+          export EDITOR=${choice:t}
+          export VISUAL=${choice:t}
+          export SUDO_EDITOR=${choice:t}
+        fi
+      done
+    fi
 
-	  # clean up after ourself
-	  trap "rm -f ${TMPZONEFILE}; exit;" 0 1 2 15
+    LOCKFILE=${TMP:-${ROOT:-/}tmp}/${DOMAIN}.lock
+    if test -r ${LOCKFILE}
+    then
+      echo "${BOLD}Found existing lock file. If you are certain nobody is editing this zone file, remove ${LOCKFILE} and try again.${NORMAL}"
+    else
 
-          read ready\?"About to edit temporary zone file for ${DOMAIN}. Do NOT change the serial number (press <ENTER> to continue). "
-          sudoedit ${TMPZONEFILE}
+      # remove the lock file under most exit conditions
+      trap "rm -f ${LOCKFILE} ; exit ;" 0 1 2 15
 
-	  # cmp returns success if the files are identical
-          if ! cmp ${zoneFile} ${TMPZONEFILE} > /dev/null 2>&1
+      if zoneFile=$(getZoneFile ${DOMAIN})
+      then
+        # get current zone file meta info (owner, group, perms, etc.)
+        stat -o -H zoneFileMeta ${zoneFile}
+
+        if TMPZONEFILE=$(mktemp -t ${zoneFile:t}-XXXXXXX)
+        then
+          if cp -p ${zoneFile} ${TMPZONEFILE}
           then
 
-            (( VERBOSE )) && echo "Updating the serial number in ${TMPZONEFILE}." >&2
-            if newSerialNumber ${TMPZONEFILE}
+            # clean up after ourself
+            trap "rm -f ${TMPZONEFILE}; exit;" 0 1 2 15
+
+            read ready\?"${BOLD}About to edit temporary zone file for ${DOMAIN}. Do NOT change the serial number (press <ENTER> to continue).${NORMAL} "
+            sudoedit ${TMPZONEFILE}
+
+            # cmp returns success if the files are identical
+            if ! cmp ${zoneFile} ${TMPZONEFILE} > /dev/null 2>&1
             then
 
-              read ready\?"Press <Enter> to view differences between the old and new zone files: "
-              (
-		# this is disgusting, but it enables us to display aligned column headers over the sdiff output
-		current="  CURRENT CONFIGURATION  "
-		new="  NEW CONFIGURATION  "
-		cLen=$(echo "${current}" | wc -c)
-		nLen=$(echo "${new}"|wc -c)
-		c=$(( ( COLUMNS / 4 ) - ( cLen / 2 ) ))
-		s=$(( COLUMNS / 2 - ( c + cLen ) ))
-		n=$(( ( COLUMNS / 4 * 3 - ( nLen / 2 )) - ( c + cLen + s ) ))
-		echo | perl -ne "print q( ) x ${c}, q(${current}), q( ) x ${s}, q(|), q( ) x ${n}, q(${new}), qq(\n);"
-		sdiff -w${COLUMNS} --suppress-common-lines --ignore-all-space ${zoneFile} ${TMPZONEFILE}
-	      ) | less -M -PM"- less (Press q to quit)- ?f%f\ ..?ltline\ %lt\ .?e(END)%t"
-
-              read ready\?"Press <Enter> to commit changes to ${zoneFile}. Press <Ctrl-C> to abort this change: "
-              if mv ${TMPZONEFILE} ${zoneFile}
+              (( VERBOSE )) && echo "Updating the serial number in ${TMPZONEFILE}." >&2
+              if newSerialNumber ${TMPZONEFILE}
               then
-                # restore perms from the original zone file
-		# we have to strip off the left-most four octal digits else chmod gets confused
-                chmod ${zoneFileMeta[mode]#????} ${zoneFile}
-                chown ${zoneFileMeta[uid]}:${zoneFileMeta[gid]} ${zoneFile}
 
-                (( VERBOSE )) && echo "Publishing DNS changes..." >&2
-                if ! pushChanges ${DOMAIN}
+		# perform some screen real estate calculations, then display the differences (paginated with less(1))
+                read ready\?"${BOLD}Press <Enter> to view differences between the old and new zone files:${NORMAL} "
+		(
+		  # this is disgusting, but it enables us to display
+		  # aligned column headers over the sdiff output
+                  current="CURRENT CONFIGURATION"
+                  new="   NEW CONFIGURATION "
+                  cLen=${#current} # string length
+                  nLen=${#new}
+                  c=$(( ( COLUMNS / 4 ) - ( cLen / 2 ) ))
+                  s=$(( COLUMNS / 2 - ( c + cLen ) ))
+                  n=$(( ( COLUMNS / 4 * 3 - ( nLen / 2 )) - ( c + cLen + s ) ))
+                  echo | perl -ne "print q( ) x ${c}, q(${current}), q( ) x ( ${s} + ${n} ), q(${new}), qq(\n);"
+                  echo | perl -ne "print q(-) x ${COLUMNS}, qq(\n);"
+
+		  # display the difference between the current and changed (temporary) zone files
+                  sdiff -w${COLUMNS:-80} --suppress-common-lines --ignore-all-space ${zoneFile} ${TMPZONEFILE}
+                ) | less -M -PM"- less (Press q to quit)- ?f%f\ ..?ltline\ %lt\ .?e(END)%t"
+
+                read ready\?"Press <Enter> to commit changes to ${zoneFile}. ${BOLD}Press <Ctrl-C> to abort this change:${NORMAL} "
+                if mv ${TMPZONEFILE} ${zoneFile}
                 then
-                  echo "Could not publish DNS changes (${?}). Contact sysadmin@wins.net."
+                  # restore perms from the original zone file
+                  # we have to strip off the left-most four octal digits else chmod gets confused
+                  chmod ${zoneFileMeta[mode]#????} ${zoneFile}
+                  chown ${zoneFileMeta[uid]}:${zoneFileMeta[gid]} ${zoneFile}
+
+                  (( VERBOSE )) && echo "Publishing DNS changes..." >&2
+                  if ! pushChanges ${DOMAIN}
+                  then
+                    echo "${BOLD}Could not publish DNS changes (${?}). Contact sysadmin@wins.net.${NORMAL}"
+                  fi
+                else
+                  echo "${BOLD}Could not replace ${zoneFile} with ${TMPZONEFILE} (${?}). Please contact sysadmin@wins.net.${NORMAL}"
                 fi
               else
-                echo "Could not replace ${zoneFile} with ${TMPZONEFILE} (${?}). Please contact sysadmin@wins.net."
+                echo "${BOLD}Error updating the serial number in ${TMPZONEFILE} (${?}). Please edit this file again or contact sysadmin@wins.net.${NORMAL}"
               fi
             else
-              echo "Error updating the serial number in ${TMPZONEFILE} (${?}). Please edit this file again or contact sysadmin@wins.net."
+              echo "${BOLD}Did not detect any changes to ${zoneFile}. NOT pushing changes to name servers.${NORMAL}"
             fi
           else
-            echo "Did not detect any changes to ${zoneFile}. NOT pushing changes to name servers."
+            echo "${BOLD}Could not copy ${zoneFile} to ${TMPZONEFILE}. Please contact sysadmin@wins.net.${NORMAL}"
           fi
         else
-          echo "Could not copy ${zoneFile} to ${TMPZONEFILE}."
+          echo "${BOLD}Could not create temporary filename: mktemp failed (${?}). Please contact sysadmin@wins.net.${NORMAL}"
         fi
       else
-        echo "Could not create temporary file (${?}). Please correct issues and try again."
+        echo "${BOLD}Could not determine the zone file for domain ${DOMAIN}. Please ensure you entered the correct domain name.${NORMAL}"
       fi
-    else
-      echo "Could not determine the zone file for domain ${DOMAIN}. Please ensure you entered the correct domain name."
     fi
-  fi # LOCKFILE check
+  else
+    echo "${BOLD}Please specify a domain name to edit.${NORMAL}"
+    usage
+  fi
 fi
-
-
-# src_backup="/var/named/primary/backup/$zone.bak"
-# src_lock="$src_file.lock"
-# final_cmd="sudo /usr/local/bin/dns reload"
-# final_msg="$src_file changed, running ${final_cmd}..."
-
-# if [ ! -f $src_file ]; then
-#       echo "The src_file $src_file doesn't exist!"
-#       exit 1
-# fi
-
-# # Check existing lock src_file.
-# if [ -f "$src_lock" ]; then
-#       echo
-#       echo "Lock file present, $src_file is currently being editted by someone else."
-#       echo "`ls -al $src_lock`"
-#       echo "Exiting."
-#       echo
-#       exit 0
-# fi
-
-# # Touch lock file
-# $touchcmd "$src_lock"
-
-# # Backup current alias file
-# if [ -f "$src_backup" ]; then
-#       $rmcmd -f "$src_backup"
-# fi
-# $cpcmd "$src_file" "$src_backup"
-# $chmodcmd 644 "$src_backup"
-
-# # Check if alternate editor defined
-# # If it is and you are not root, set editor to pico
-# # Unsave to allow user's editor to be VI when sudoing!
-
-# if [ $EDITOR ]; then
-#       editorcmd=$EDITOR
-# else
-#       editorcmd=${default_editor}
-# fi
-
-# $editorcmd "$src_file"
-
-# # Editting done, remove the lock file
-# $rmcmd "$src_lock"
-
-# # See if any changes made
-# output="`$diffcmd $src_file $src_backup`"
-# if [ "$output" ]; then
-#       echo
-#       echo -e "\tChecking zone ${zone}\n\tNOTE: the 'loaded' message does NOT mean named was reloaded ...\n"
-#       if ${checkzone} ${zone} ${src_file}
-#       then
-#               echo
-#               echo "Would you like to reload DNS? (y/n)"
-#               read answer
-
-#               if [ "$answer" = "y" ]; then
-#                       echo "$final_msg"
-#                       $final_cmd
-#               fi
-#       else
-#               echo "Check of zone failed. Please correct this zone and re-run editdns"
-#       fi
-# else
-#         echo
-#         echo "No changes were made to $src_file , exiting."
-#         echo
-# fi
 
 exit
 
